
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_ENV: docker
      DOCKERIZED: "1"
      POSTGRES_HOST: db
      PUBLIC_BASE_URL: http://localhost:8000
      # Esto asegura que la lib de Google use la credencial montada
      GOOGLE_APPLICATION_CREDENTIALS: /app/key.json
      # (opcional) si no usas GOOGLE_APPLICATION_CREDENTIALS:
      # GEE_KEY_PATH: /app/key.json
    volumes:
      - ./:/app/:cached
      - ./key.json:/app/key.json:ro
    depends_on:
      - db
    command: >
      sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    profiles: ["dev"]

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_ENV: production
      DOCKERIZED: "1"
      POSTGRES_HOST: db
      PUBLIC_BASE_URL: http://localhost:8000
      GOOGLE_APPLICATION_CREDENTIALS: /app/key.json
    depends_on:
      - db
    # sin volumes ni --reload
    profiles: ["prod"]

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
