
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_ENV: docker
      DOCKERIZED: "1"
      POSTGRES_HOST: db
      PUBLIC_BASE_URL: http://localhost:8000
      # Esto asegura que la lib de Google use la credencial montada
      GOOGLE_APPLICATION_CREDENTIALS: /app/key.json
      # (opcional) si no usas GOOGLE_APPLICATION_CREDENTIALS:
      # GEE_KEY_PATH: /app/key.json
    volumes:
      - ./:/app/:cached
      - ./key.json:/app/key.json:ro

    profiles: ["dev"]

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_ENV: production
      DOCKERIZED: "1"
      POSTGRES_HOST: db
      PUBLIC_BASE_URL: http://localhost:8000
      GOOGLE_APPLICATION_CREDENTIALS: /app/key.json

    # sin volumes ni --reload
    profiles: ["prod"]

  
volumes:
  postgres_data:
